<template>
  <div class="loadingio-spinner-spinner-167ckfbjhzi">
    <div class="ldio-6kd4qg6oe27">
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
    </div>
  </div>
</template>

<script setup></script>

<style scoped>
@keyframes ldio-6kd4qg6oe27 {
  0% {
    opacity: 1;
  }
  100% {
    opacity: 0;
  }
}
.ldio-6kd4qg6oe27 div {
  left: 90px;
  top: 45px;
  position: absolute;
  animation: ldio-6kd4qg6oe27 linear 1s infinite;
  background: #009499;
  width: 20px;
  height: 30px;
  border-radius: 10px / 15px;
  transform-origin: 10px 55px;
}
.ldio-6kd4qg6oe27 div:nth-child(1) {
  transform: rotate(0deg);
  animation-delay: -0.875s;
  background: #009499;
}
.ldio-6kd4qg6oe27 div:nth-child(2) {
  transform: rotate(45deg);
  animation-delay: -0.75s;
  background: #009499;
}
.ldio-6kd4qg6oe27 div:nth-child(3) {
  transform: rotate(90deg);
  animation-delay: -0.625s;
  background: #009499;
}
.ldio-6kd4qg6oe27 div:nth-child(4) {
  transform: rotate(135deg);
  animation-delay: -0.5s;
  background: #009499;
}
.ldio-6kd4qg6oe27 div:nth-child(5) {
  transform: rotate(180deg);
  animation-delay: -0.375s;
  background: #009499;
}
.ldio-6kd4qg6oe27 div:nth-child(6) {
  transform: rotate(225deg);
  animation-delay: -0.25s;
  background: #009499;
}
.ldio-6kd4qg6oe27 div:nth-child(7) {
  transform: rotate(270deg);
  animation-delay: -0.125s;
  background: #009499;
}
.ldio-6kd4qg6oe27 div:nth-child(8) {
  transform: rotate(315deg);
  animation-delay: 0s;
  background: #009499;
}
.loadingio-spinner-spinner-167ckfbjhzi {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: rgba(NaN, NaN, NaN, 0);
}
.ldio-6kd4qg6oe27 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-6kd4qg6oe27 div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
